### ISSUE TITLE
Staff Photos

### ISSUE THREAD

**Issue by carlsong88** [lighthousemontessori/lighthousemontessori.github.io#1]
![jasonsquare](https://cloud.githubusercontent.com/assets/9835028/7777454/072a2e00-0078-11e5-84bb-363d8938473d.jpg)

**Comment by jeremylightsmith** [comment]
This is uploaded, and I cleaned up the page code, so it should be much easier to keep up to date. Also, I need abby's picture, and we need quotes from both of them.
